apiVersion: v1
kind: ConfigMap
metadata:
  name: bashrc-{{ .Values.user }}
  namespace: {{ .Values.namespace }}
data:
  .bashrc: |
    echo Checking XTERM - $XTERM_VERSION ...
    if [ -n "$XTERM_VERSION" ]; then
        echo "XTERM_VERSION is set to $XTERM_VERSION — starting script..."
        cd /workspace/usu/rc-client
        ./admin.sh
    fi