apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-{{ .Values.user }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp
      user: {{ .Values.user }}
  template:
    metadata:
      labels:
        app: myapp
        user: {{ .Values.user }}
    spec:
      containers:
        - name: myapp
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 80    # VNC/noVNC GUI
            - containerPort: 8087  # Web-Frontend
          volumeMounts:
            - name: shared-data
              mountPath: /data
      volumes:
        - name: shared-data
          persistentVolumeClaim:
            claimName: myapp-{{ .Values.user }}-pvc
