apiVersion: v1
kind: ConfigMap
metadata:
  name: novnc-index-{{ .Values.user }}
  namespace: {{ .Values.namespace }}
data:
  index.html: |
    <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN">
    <html><head>
      <meta http-equiv="refresh" content="0; URL=gui/vnc_auto.html">
    </html>


