apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: myapp-{{ .Values.user }}-pvc
  namespace: {{ .Values.namespace }}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.storage.size }}