apiVersion: v1
kind: Service
metadata:
  name: myapp-{{ .Values.user }}-svc
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: myapp
    user: {{ .Values.user }}
  ports:
    - name: vnc
      port: 80
      targetPort: 80
    - name: frontend
      port: 8087
      targetPort: 8087
