[supervisord]
user=usuuser
logfile=/workspace/usu/data/log/supervisord.log
logfile_maxbytes=50MB
logfile_backups=10
loglevel=debug
pidfile=/tmp/supervisord.pid
nodaemon=false

[program:Xvfb]
command=/usr/bin/Xvfb :1 -screen 0 1920x1080x16
autostart=true
autorestart=true
priority=1
environment=DISPLAY=":1"

[program:fluxbox]
command=/usr/bin/fluxbox
autostart=true
autorestart=true
priority=2
environment=DISPLAY=":1"

[program:xterm]
command=/usr/bin/xterm
autostart=true
autorestart=true
priority=3
environment=DISPLAY=":1"

[program:x11vnc]
command=/usr/bin/x11vnc -display :1 -forever -nopw -shared
autostart=true
autorestart=true
priority=4

[program:novnc]
command=/usr/share/novnc/utils/launch.sh --vnc localhost:5900 --listen 8080 --web /usr/share/novnc
# das geht wohl nicht aber warum? IN .05 ging es wohl --path /user456/gui
autostart=true
autorestart=true
stdout_logfile=/workspace/usu/data/log/novnc.out.log
stderr_logfile=/workspace/usu/data/log/novnc.err.log
priority=5

[program:uploadserver]
command=python3 /workspace/usu/uploadserver.py
directory=/workspace/usu
autostart=true
autorestart=true
stderr_logfile=/workspace/usu/data/log/uploadserver.err.log
stdout_logfile=/workspace/usu/data/log/uploadserver.out.log
user=usuuser

#Umleitung der Log-Asugaben direkt in das Log des Pods:
#/dev/stdout oder /dev/stderr umleiten


# [supervisord]
# logfile=/workspace/usu/data/supervisord.log
# logfile_maxbytes=50MB
# logfile_backups=10
# loglevel=info
# pidfile=/tmp/supervisord.pid
# nodaemon=false
# minfds=1024
# minprocs=200

# [program:xterm]
# command=xterm
# autostart=true
# autorestart=true
