; Minimal xrdp_keyboard.ini für deutsches Tastaturlayout

[default]
keyboard_type=4
keyboard_subtype=1
rdp_layouts=default_rdp_layouts
layouts_map=default_layouts_map

[default_rdp_layouts]
rdp_layout_de=0x00000407

[default_layouts_map]
rdp_layout_de=de
