[Globals]
ListenAddress=127.0.0.1
ListenPort=3350
EnableUserWindowManager=true
# Falls du ein zentrales Startskript verwenden willst:
#UserWindowManager=/etc/xrdp/startwm.sh
#DefaultWindowManager=startxfce4

[Security]
AllowRootLogin=true
MaxLoginRetry=4
TerminalServerUsers=tsusers
TerminalServerAdmins=tsadmins
AlwaysGroupCheck=false

[Sessions]
X11DisplayOffset=10
MaxSessions=50
KillDisconnected=true
DisconnectedTimeLimit=0
IdleTimeLimit=0
Policy=Default

[Xvnc]
#param=/usr/local/bin/xvnc-wrapper.sh
param=/usr/bin/Xvnc
param=-bs
param=-nolisten
param=tcp
param=-localhost
param=-dpi
param=96
param=-geometry
param=1920x1080
param=-depth
param=24
# param=-SecurityTypes
# param=None
#param=-xkbmap
#param=de
# Entfernt, da du keine VNC-Passwortdatei nutzt:
#param=-rfbauth
#param=/etc/xrdp/vncpasswd

[Logging]
LogFile=/var/log/xrdp-sesman.log
LogLevel=DEBUG
EnableSyslog=false
SyslogLevel=DEBUG