[Globals]
ListenAddress=127.0.0.1
ListenPort=3350
EnableUserWindowManager=true
#UserWindowManager=/etc/xrdp/startwm.sh
#DefaultWindowManager=startxfce4

[Security]
AllowRootLogin=true
MaxLoginRetry=4
TerminalServerUsers=tsusers
TerminalServerAdmins=tsadmins
AlwaysGroupCheck=false

[Sessions]
X11DisplayOffset=10
MaxSessions=50
KillDisconnected=true
DisconnectedTimeLimit=0
IdleTimeLimit=0
Policy=Default

[Xvnc]
param=Xvnc
param=-bs
param=-nolisten
param=tcp
param=-localhost
param=-dpi
param=96
param=-geometry
param=1280x800
param=-depth
param=24
param=-rfbauth
param=/etc/xrdp/vncpasswd
