apiVersion: apps/v1
kind: Deployment
metadata:
  name: rc-{{ .Values.user }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rc
      user: {{ .Values.user }}
  template:
    metadata:
      labels:
        app: rc
        user: {{ .Values.user }}
    spec:
      imagePullSecrets:
        {{- toYaml .Values.imagePullSecrets | nindent 8 }}
      serviceAccountName: rc-{{ .Values.user }}-svca
      containers:
        - name: rc
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          
          env:
            - name: TZ
              value: Europe/Berlin
            - name: HOME
              value: "/home/tomcat"
            # - name: DISPLAY_WIDTH
            #   value: "1600"
            # - name: DISPLAY_HEIGHT
            #   value: "900"
            - name: CATALINA_BASE
              value: "/usr/share/tomcat9"
            # Benutzer und PW codieren
            - name: RDP_USERNAME
              valueFrom:
                secretKeyRef:
                  name: rc-user-secret
                  key: username
            - name: RDP_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: rc-user-secret
                  key: password
            - name: GEOMETRY
              value: ${GEOMETRY:-{{ .Values.Geometry }}}
            - name: DEPTH
              value: ${DEPTH:-{{ .Values.Depth }}}
          # 11.06.2025 - den Container am Leben halten für 10h
          # 26.06.2025 - ADD special user
          #echo "Hello, Kubernetes! I am $(whoami)" && echo "My home directory: $HOME" && 
          # command: ["sh", "-c", '/usr/bin/supervisord -c /etc/supervisor/supervisord.conf && tail -f /dev/stdout']
          command: 
            - sh
            - -c
            - | 
              useradd -m -s /bin/bash "$RDP_USERNAME" 2>/dev/null && \
              echo "$RDP_USERNAME:$RDP_PASSWORD" | chpasswd && \
              cp /home/tomcat/.xsession /home/$RDP_USERNAME && \
              cp -r /home/tomcat/.valuemation /home/$RDP_USERNAME && \
              chmod +x /home/$RDP_USERNAME/.xsession && \
              chown -R $RDP_USERNAME:$RDP_USERNAME /home/$RDP_USERNAME && \
              mkdir -p /run/xrdp/sockdir && \
              chown xrdp:xrdp /run/xrdp /run/xrdp/sockdir && \
              echo "#!/bin/bash\ncd /workspace/usu/rc-client\nexec xterm -e ./admin.sh " >/home/$RDP_USERNAME/.xsession && \
              echo "LANG=de_DE.UTF-8\nLANGUAGE=de_DE:de\nLC_ALL=de_DE.UTF-8" > /etc/default/locale && \
              { echo "auth required pam_debug.so"; cat /etc/pam.d/xrdp-sesman; } > temp && mv temp /etc/pam.d/xrdp-sesman && \
              sed -i '/^# *de_DE.UTF-8 UTF-8/s/^# *//' /etc/locale.gen && \
              locale-gen && \
              usermod -aG shadow tomcat && \
              /usr/bin/supervisord -c /etc/supervisor/supervisord.conf && \
              tail -f /dev/stdout
          
          #chmod +x /usr/local/bin/xvnc-wrapper.sh && \
          # It is for running as the root user
          securityContext:
            runAsUser: 0
          
          ports:
            - containerPort: 8080   # Guacamole Web
            - containerPort: 8087   # Jetty
            - containerPort: 8000   # Uploadserver
            - containerPort: 3389   # RDP
            - containerPort: 4822   # guacd
          
            
# 19.6.25 dynamisch die loginconfigurations.xml aufbauen
          volumeMounts:
            - name: login-config
              mountPath: /home/tomcat/.valuemation/loginConfigurations.xml
              subPath: loginConfigurations.xml
            - name: flask
              mountPath: /workspace/usu/uploadserver.py
              subPath: uploadserver.py
            - name: setenvuser
              mountPath: /workspace/usu/rc-client/set_env_user.sh
              subPath: set_env_user.sh
            - name: user-mapping
              mountPath: /etc/guacamole/user-mapping.xml
              subPath: user-mapping.xml
            - name: tomcat-web
              mountPath: /usr/share/tomcat9/conf/web.xml
              subPath: web.xml
            - name: guacamole-properties
              mountPath: /etc/guacamole/guacamole.properties
              subPath: guacamole.properties
            - name: sesman-ini
              mountPath: /etc/xrdp/sesman.ini
              subPath: sesman.ini
            - name: xrdp-ini
              mountPath: /etc/xrdp/xrdp.ini
              subPath: xrdp.ini
            - name: supervisord-conf
              mountPath: /etc/supervisor/supervisord.conf
              subPath: supervisord.conf
            - name: valuemation-config
              mountPath: /home/tomcat/.valuemation/valuemation.ini
              subPath: valuemation.ini
            # - name: xvnc-wrapper
            #   mountPath: /usr/local/bin/xvnc-wrapper.sh
            #   subPath: xvnc-wrapper.sh
          resources:
            {{- toYaml .Values.resources | nindent 12 }}

      volumes:
        - name: login-config
          configMap:
            name: login-config-{{ .Values.user }}
        - name: flask
          configMap:
            name: flask-uploadsrv-{{ .Values.user }}
        - name: setenvuser
          configMap:
            name: setenvuser-{{ .Values.user }}
        - name: user-mapping
          configMap:
            name: guacamole-user-mapping-{{ .Values.user }}
        - name: tomcat-web
          configMap:
            name: guacamole-tomcat-web-mapping-{{ .Values.user }}
        - name: guacamole-properties
          configMap:
            name: guacamole-properties-mapping-{{ .Values.user }}
        - name: sesman-ini
          configMap:
            name: sesman-ini-{{ .Values.user }}
        - name: xrdp-ini
          configMap:
            name: xrdp-ini-{{ .Values.user }}
        - name: supervisord-conf
          configMap:
            name: supervisord-conf-{{ .Values.user }}
        - name: valuemation-config
          configMap:
            name: valuemation-config-{{ .Values.user }}
        # - name: xvnc-wrapper
        #   configMap:
        #     name: xvnc-wrapper-{{ .Values.user }}
