#wird so nicht mehr benötigt da im Basis Image bereits kopiert
apiVersion: v1
kind: ConfigMap
metadata:
  name: guacamole-properties-mapping-{{ .Values.user }}
data:
  guacamole.properties: |
    auth-provider: net.sourceforge.guacamole.net.basic.BasicFileAuthenticationProvider
    basic-user-mapping: /etc/guacamole/user-mapping.xml
    guacd-hostname: localhost
    guacd-port: 4822
    enable-clipboard-autopaste: true

    # --- OpenID Connect (Keycloak) ---
    openid-issuer: {{ .Values.openid.issuer }}
    openid-client-id: {{ .Values.openid.clientId }}
    openid-client-secret: {{ .Values.openid.clientSecret }}
    #openid-client-secret: ${GUAC_OIDC_CLIENT_SECRET} # das wird zur Laufzeit nicht ersetzt

    # Keycloak realm endpoints (realm: master)
    openid-authorization-endpoint: {{ .Values.openid.authorizationEndpoint }}
    openid-token-endpoint:         {{ .Values.openid.tokenEndpoint }}
    openid-jwks-endpoint:          {{ .Values.openid.jwksEndpoint }}
    openid-userinfo-endpoint:      {{ .Values.openid.userinfoEndpoint }}

    # Redirect must match Keycloak client redirect URI
    openid-redirect-uri: {{ .Values.openid.redirectUri }}

    # Username that Guacamole will use internally (must match user-mapping.xml usernames)
    openid-username-claim-type: preferred_username