apiVersion: v1
kind: ConfigMap
metadata:
  name: guacamole-user-mapping-{{ .Values.guacamole.username }}
data:
  user-mapping.xml: |
    <user-mapping>
      <authorize 
          username="{{ .Values.guacamole.username }}" 
          password="{{ .Values.guacamole.password }}">
        <connection name="Jetty-Rich-Client">
          <protocol>rdp</protocol>
          <param name="hostname">127.0.0.1</param>
          <param name="port">3389</param>
          <param name="username">{{ .Values.rdp.username }}</param>
          <param name="password">{{ .Values.rdp.password }}</param>
        </connection>
      </authorize>
    </user-mapping>
