apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: rc-{{ .Values.user }}-guacamole-ingress
  namespace: {{ .Values.namespace }}  
  {{- if .Values.ingress.annotations }}
  annotations:
    {{- toYaml .Values.ingress.annotations | nindent 4 }}
  {{- end }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  {{- if .Values.ingress.tls }}
  tls:
    - hosts:
        - {{ .Values.ingress.hostname }}
      secretName: tls-{{ .Values.user }}
  {{- end }}
  rules:
    - host: {{ .Values.ingress.hostname }}
      http:
        paths:
          - path: /guacamole
            pathType: Prefix #ImplementationSpecific
            backend:
              service:
                name: rc-{{ .Values.user }}-svc
                port:
                  number: 80
          - path: /guacamole/
            pathType: Prefix #ImplementationSpecific
            backend:
              service:
                name: rc-{{ .Values.user }}-svc
                port:
                  number: 80
