apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: rc-{{ .Values.user }}-ingress
  namespace: {{ .Values.namespace }}  
    {{- if .Values.ingress.annotations }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-request-buffering: "off"
    nginx.ingress.kubernetes.io/proxy-http-version: "1.1"
    nginx.ingress.kubernetes.io/connection-proxy-header: "keep-alive"
    {{- if .Values.ingress.annotations }}
    {{- toYaml .Values.ingress.annotations | nindent 4 }}
    {{- end }}
  {{- end }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  {{- if .Values.ingress.tls }}
  tls:
    - hosts:
        - {{ .Values.ingress.hostname }}
      secretName: tls-{{ .Values.user }}
  {{- end }}
  rules:
    - host: {{ .Values.ingress.hostname }}
      http:
        paths:
          - path: /{{ .Values.user }}/jetty(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: rc-{{ .Values.user }}-svc
                port:
                  number: 8087
# 28.06.2026 Upload und Download Server
          - path: /{{ .Values.user }}/transfer(/|$)(.*)
            pathType: ImplementationSpecific
            #pathType: Prefix
            backend:
              service:
                name: rc-{{ .Values.user }}-svc
                port:
                  number: 8000

