apiVersion: v1
kind: Secret
metadata:
  name: rc-user-secret
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  username: {{ required "❌ .Values.user is required (--set user=...)" .Values.user | b64enc }}
  password: {{ required "❌ .Values.pw is required (--set pw=...)" .Values.pw | b64enc }}
