apiVersion: v1
kind: Service
metadata:
  name: rc-{{ .Values.user }}-svc
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: rc
    user: {{ .Values.user }}
  ports:
    - name: vnc
      port: 80
      targetPort: 8080
    - name: webjetty
      port: 8087
      targetPort: 8087
    - name: transfer
      port: 8000
      targetPort: 8000
      
# 09.06.2025 ergänzt um auf den Port zugreifen zu können      
    # - name: rfb
    #   port: 5900
    #   targetPort: 5900
    # - name: novnc
    #   port: 6000
    #   targetPort: 6000
# 23.06.25 Transfer Upload/ Download
    # - name: webdav
    #   port: 8081
    #   targetPort: 8081
