apiVersion: v1
kind: ConfigMap
metadata:
  name: user-xsession-{{ .Values.user }}
data:
  .xsession: |
    #!/bin/bash

    # Setze deutsche UTF-8 Locale
    export LANG=de_DE.UTF-8
    export LC_ALL=de_DE.UTF-8
    export XRDP_SOCKET_PATH=/tmp

    # Setze deutsches Tastaturlayout (QWERTZ) ohne "Tottasten"
    setxkbmap -layout de -variant nodeadkeys

    # Starte Openbox als Fenstermanager
    openbox &

    # Starte Clipboard-Manager (für Copy & Paste)
    diodon &

    # Starte dein eigenes Menü-Skript im modernen Terminal
    xfce4-terminal --title="Session-Start" --command="$HOME/.menu-xsession"
    
