#wird über Ressources initial befüllt und so nicht mehr notwendig
apiVersion: v1
kind: ConfigMap
metadata:
  name: xrdp-ini-{{ .Values.user }}
data:
  xrdp.ini: |
    [Globals]
    ini_version=1
    fork=true
    port=3389
    use_unix_socket=true
    use_vsock=false
    tcp_nodelay=true
    tcp_keepalive=true
    security_layer=rdp
    crypt_level=high  ; <---- war vorher high
    ssl_protocols=TLSv1.2, TLSv1.3
    allow_channels=true
    allow_multimon=true
    bitmap_cache=true
    bitmap_compression=true
    bulk_compression=true
    max_bpp=32
    new_cursors=true
    autorun=Xvnc  ; <--- wichtig: startet automatisch die Xvnc-Session


    [Logging]
    LogFile=/var/log/xrdp.log
    LogLevel=DEBUG
    EnableSyslog=true

    [Channels]
    rdpdr=true
    rdpsnd=true
    drdynvc=true
    cliprdr=true
    rail=true
    xrdpvr=true
    tcutils=true

    [xrdp1]
    name=Xvnc
    lib=libvnc.so
    username=ask
    password=ask
    ip=127.0.0.1
    port=-1

