# # Kubernetes Namespace für die App
# namespace: consult-usimheinz-202516
# helm upgrade --install jetty-usifhirsch ./jetty-helm --namespace consult-usimheinz-202516 --set user="" --set pw=""

#### CHANGE ALWAYS ####
# search for the namespace and replace it in this file!
namespace: consult-usimheinz-202516
# change also the database password!!!
#######################

# Benutzer und PW werden zusammengefasst und in secret codiert
user: ""
pw: ""
# #Username of Consultant
# # user: usifhirsch
# # userpw: changeIt
# guacamole:
#   username: usifhirsch
#   password: geheim123

# rdp:
#   #host: 
#   #rc-usifhirsch-svc.consult-usimheinz-202516.k8s-dev004.aspera.usu.grp
#   #rc-usifhirsch-svc.consult-usimheinz-202516.svc.cluster.local
#   #port: 3389
#   username: usifhirsch
#   password: rdppass
Geometry: 1920x1080
Depth: 24
enablePersistence: false

image:
  repository: frank1977/jetty-rich-client
  tag: usm5.5.01.57
# funktionierte gut, ohne upload server    tag: usm5.5.01.08
#.05 hat im Web funktioniert

  pullPolicy: Always


imagePullSecrets:
  - name: usu-regcred

ingress:
  enabled: true
  className: nginx
  certManager: true
  annotations:
    cert-manager.io/cluster-issuer: usu-group-issuer
  hostname: rc.consult-usimheinz-202516.k8s-dev004.aspera.usu.grp
  tls: true

storage:
  size: 1Gi
  storageClassName: vsphere-csi-sc

resources:
  limits:
    memory: 4Gi
  requests:
    cpu: 1000m
    memory: 2Gi

# depends on the USC Package secrets.yaml
db:
  host: usm-mariadb.consult-usimheinz-202516.svc.cluster.local
  port: "3306"
  dbase: usm
  qualifier: ""
  dbuser: root
  #here is the secrets.yaml - usmMariadbRootPassword: 
  dbpassword: changeMeR562zoUI2tX6
  
  dbaseexport: usm_export
  dbasectm: usmctm
  dbasehistory: usm_history
  dbasetest: usm_archive
