# # Kubernetes Namespace für die App
# namespace: consult-usifhirsch-202525
# helm upgrade --install jetty-usifhirsch ./jetty-helm --namespace consult-usifhirsch-202525 --set user="" --set pw=""

#### CHANGE ALWAYS ####
# search for the namespace and replace it in this file!
namespace: consult-usifhirsch-202525
# change also the database password!!!
#######################

# Benutzer und PW werden zusammengefasst und in secret codiert
user: ""
pw: ""
# #Username of Consultant
# # user: usifhirsch
# # userpw: changeIt
# guacamole:
#   username: usifhirsch
#   password: geheim123

# rdp:
#   #host: 
#   #rc-usifhirsch-svc.consult-usifhirsch-202525.k8s-dev004.aspera.usu.grp
#   #rc-usifhirsch-svc.consult-usifhirsch-202525.svc.cluster.local
#   #port: 3389
#   username: usifhirsch
#   password: rdppass
Geometry: 1920x1080
Depth: 24
enablePersistence: false

image:
  version: v3.0
  repository: frank1977/jetty-rich-client
  tag: usm5.5.02.07 # mit orchestra
#  tag: usm5.5.02.06 # ok, mit kubectl und vim
#  tag: usm5.5.02.04 # ok aber noch falsches Tastaturlayout  
#  tag: usm5.5.01.70 muss getestet werden!
#   tag: usm5.5.01.69 # fehlerhaft
#  tag: usm5.5.01.68 # ok aber noch falsches Tastaturlayout
#  tag: usm5.5.01.57  # fehlerhaft
#  tag: usm5.5.01.56  # fehlerhaft
#  tag: usm5.5.01.55  # Openbox funktioniert einwandfrei
#  tag: usm5.5.01.61  Stand geht nicht
# funktionierte gut, ohne upload server    tag: usm5.5.01.08
#.05 hat im Web funktioniert

  pullPolicy: IfNotPresent

imagePullSecrets:
  - name: usu-regcred

ingress:
  enabled: true
  className: nginx
  certManager: true
  annotations:
    cert-manager.io/cluster-issuer: usu-group-issuer
  hostname: rc.consult-usifhirsch-202525.k8s-dev004.aspera.usu.grp
  tls: true
  uploadlimit: 800 #MB

transfer:
  filetypes: "zip,xml,sql,psc"

storage:
  size: 1Gi
  storageClassName: vsphere-csi-sc

resources:
  limits:
    memory: 4Gi
  requests:
    cpu: 1000m
    memory: 2Gi

# depends on the USC Package secrets.yaml
db:
  host: usm-mariadb.consult-usifhirsch-202525.svc.cluster.local
  port: "3306"
  dbase: usm
  qualifier: ""
  dbuser: root
  #here is the secrets.yaml - usmMariadbRootPassword: 
  dbpassword: changeMeO54aVCMUb06D
  #2025.2.4 changeMePLFnw8fLVvz0
  #2025.2.3 changeMeIl0MKYTBxlwn
  #2025.2.0 changeMe7IMuzjS4W5NR
  
  dbaseexport: usm_export
  dbasectm: usmctm
  dbasehistory: usm_history
  dbasetest: usm_archive
