handlers = java.util.logging.ConsoleHandler
java.util.logging.ConsoleHandler.level = INFO
java.util.logging.ConsoleHandler.formatter = java.util.logging.SimpleFormatter

.level = INFO

# Guacamole Logging
org.apache.guacamole.level = INFO
org.apache.guacamole.extension.level = INFO
org.apache.guacamole.protocol.level = INFO
org.apache.guacamole.net.level = INFO

# Tomcat intern
org.apache.catalina.level = INFO
org.apache.coyote.level = INFO
org.apache.tomcat.level = INFO
