# # Kubernetes Namespace für die App
namespace: consult-usifhirsch-55

user: user456
userpw: mv

enablePersistence: false

image:
  repository: frank1977/jetty-rich-client
  tag: usm5.5.01.06
  pullPolicy: Always


imagePullSecrets:
  - name: usu-regcred

ingress:
  enabled: true
  className: nginx
  certManager: true
  annotations:
    cert-manager.io/cluster-issuer: usu-group-issuer
  hostname: rc.consult-usifhirsch-55.k8s-dev001.aspera.usu.grp
  tls: true

storage:
  size: 1Gi
  storageClassName: vsphere-csi-sc

resources:
  limits:
    memory: 2Gi
  requests:
    cpu: 500m
    memory: 1Gi

db:
  host: usm-mariadb.consult-usifhirsch-55.svc.cluster.local
  port: "3306"
  dbase: usm
  qualifier: ""
  dbuser: usm
  dbpassword: changeMeP1TSgsF0CQeB
